version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: 
      context: .
      dockerfile: nuxt/Dockerfile
    volumes:
      - ./app:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

  web:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - ./doc:/usr/local/apache2/htdocs
    restart: unless-stopped
volumes:
  node_modules: